# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8dc771cecaf99665b625f7ad4ca9eb2f6de08d2a99858fd3ebff335056ea3b4170a6b0871e2b46ade5de06f7ac5712357040f37670c75c9b0c9f412def42392

test:
  secret_key_base: c5cf97c1435fe3e7259c321f85ea4b169b5f603eb7a4b3fa42ac633e1a8d5d0f6f939ebf57f38eb9db9a1ab416c6deee4261904d80aa372c6e202fa583424108

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
